import type { Sentence } from "./index";

const group = (tag: Sentence["tag"], lines: string[]): Sentence[] => lines.map((text) => ({ text, tag }));

export const en: Sentence[] = [
  ...group("vowels", [
    "The tall oak stands alone on the hill.",
    "I saw a small boat far out on the water.",
    "The old road ends at the open field.",
    "Early air feels cool over the lake.",
    "A yellow kite floated above the beach.",
    "The evening sky turned orange and gold.",
    "We ate apples under the apple tree.",
    "The echo answered from across the valley.",
    "Ice on the pond looked pale and even.",
    "Our aunt owns a house by the ocean.",
    "The moon rose over the quiet island.",
    "All the windows were open all afternoon.",
    "Eight owls sat awake on the eaves.",
    "A gentle wave washed over my feet.",
    "The air smelled of oranges and rain.",
  ]),
  ...group("nasals", [
    "Nine men mended the broken window.",
    "My mom hummed a song in the morning.",
    "The moon hung low behind the mountain.",
    "No one remembered the name of the inn.",
    "Warm bread was waiting in the kitchen.",
    "The hummingbird hovered near the honey.",
    "An amber lamp shone in the dining room.",
    "Ann brought lemons and a small melon.",
    "Some morning fog hung over the meadow.",
    "The train came in nine minutes late.",
    "Many mornings begin with a long walk.",
    "Autumn wind moved through the canyon.",
    "The engine hummed under the moonlight.",
    "A new moon means darker evenings.",
    "My cousin planted mint along the fence.",
  ]),
  ...group("fricatives", [
    "Fresh fish sizzled softly in the pan.",
    "She found five shells by the shore.",
    "The soft scarf smells of lavender.",
    "Fog filled the valley before sunrise.",
    "Thick frost covered the fields this morning.",
    "We shared a thermos of hot coffee.",
    "The shelf holds a vase and three photos.",
    "His shoes were still wet from the rain.",
    "A swift river flows past the village.",
    "Vanilla and cinnamon flavor the sauce.",
    "The zipper on the fleece finally shut.",
    "Sunshine spilled across the wooden floor.",
    "Feathers drifted over the surface of the pond.",
    "The chef served a savory vegetable soup.",
    "Leaves rustle whenever the breeze shifts.",
  ]),
  ...group("plosives", [
    "Put the cup back on the top shelf.",
    "The big dog dug a deep hole in the garden.",
    "Peter packed a bag of ripe peaches.",
    "Take the blue bike to the bottom of the block.",
    "A cat tipped the pot of paint over.",
    "Please keep the kitchen door closed.",
    "The bakery bakes bread before daybreak.",
    "Bob bought a ticket to the coast.",
    "Drop the coat on the bed by the door.",
    "The kettle clicked and the tea was ready.",
    "Pack two pairs of boots for the trip.",
    "A dark bird pecked at the bark.",
    "The carpet got damp under the potted plant.",
    "Dad built a bookcase out of pine boards.",
    "Tap the code twice to open the gate.",
  ]),
  ...group("liquids", [
    "Lily rolled the yellow ball down the hall.",
    "The river curls around the old mill.",
    "Rain fell lightly all along the lane.",
    "A little lantern lit the cellar stairs.",
    "Laura carried lilies to the railway.",
    "The lorry rolled slowly over the bridge.",
    "Real wool feels warm in early winter.",
    "Rows of lemon trees line the road.",
    "The lake looked like a silver mirror.",
    "Rachel learned to sail last summer.",
    "The lawn was still wet from the sprinkler.",
    "Larks rise early over the rolling hills.",
    "A silver bell rang from the little chapel.",
    "Roll the towels and leave them by the pool.",
    "The lighthouse glows red along the shore.",
  ]),
  ...group("questions", [
    "Would you like tea or coffee this morning?",
    "Where did you leave the garden keys?",
    "What time does the last train leave?",
    "Have you seen the new bakery on the corner?",
    "Could we go to the beach on Saturday?",
    "How old is your neighbor's dog?",
    "Is it going to rain again tonight?",
    "Does the market close early on Sundays?",
    "Do you prefer the window or the aisle?",
    "How was your trip to the coast?",
    "Has anyone seen my green umbrella?",
    "Which film should we watch tonight?",
    "Is the bread still warm, do you think?",
    "May I leave my bike by the entrance?",
    "How much is a bag of oranges today?",
  ]),
  ...group("mixed", [
    "When the rain stopped, we walked to the park and the air felt clean.",
    "The bakery opens at six, the bread comes out at seven, and the line starts before that.",
    "After lunch I read a chapter, closed the book, and dozed in the hammock.",
    "If the weather clears tomorrow, we will take the new kite to the field.",
    "The cat slept on the sofa while the rain tapped against the window.",
    "I put away the groceries, washed the dishes, and finally sat down.",
    "Late in the afternoon the sky turned orange and the wind grew cooler.",
    "She watered the plants, opened the curtains, and put on some quiet music.",
    "The drive was long, but the road was empty and the scenery was lovely.",
    "Before bed I turn off the lights, lock the door, and leave the window open.",
    "We agreed to leave early, grab a coffee, and catch the first ferry.",
    "The train left on time, crossed the bridge, and vanished among the hills.",
  ]),
];
