import type { Sentence } from "./index";

const group = (tag: Sentence["tag"], lines: string[]): Sentence[] => lines.map((text) => ({ text, tag }));

export const pt: Sentence[] = [
  ...group("vowels", [
    "A casa amarela fica ao lado da praça.",
    "Ela abriu a janela para olhar o mar.",
    "O sol aquece a areia da praia inteira.",
    "A água da cachoeira caía clara e fria.",
    "Hoje a tarde está bonita e calma.",
    "A lua apareceu cedo sobre a cidade.",
    "Eu adoro ouvir o vento nas árvores.",
    "A avó guarda a chave da sala azul.",
    "O céu aberto era todo alaranjado.",
    "Aquela ilha tem areia e coqueiros.",
    "Ela ama passear à beira do lago.",
    "A pipa subiu alta e ficou parada.",
    "O ar da manhã estava leve e úmido.",
    "Eu vi um barco azul ao longe.",
    "A sala ficou clara com a luz do dia.",
  ]),
  ...group("nasals", [
    "A manhã nasceu nublada na montanha.",
    "Minha mãe ganhou um lindo jardim.",
    "Ninguém encontrou o anel na cozinha.",
    "O menino andou até o fim da ponte.",
    "Um vento manso soprou sobre o campo.",
    "Amanhã vamos plantar manjericão.",
    "O sino da igreja tocou ao meio-dia.",
    "Nunca vi tantas mangas numa árvore só.",
    "O pão de manhã estava quentinho ainda.",
    "Meu irmão comprou lençóis novos ontem.",
    "A cantina fecha antes do fim da tarde.",
    "Um nome comum some na multidão.",
    "Tem um limão maduro em cima da mesa.",
    "Ontem à noite sonhei com um jardim imenso.",
    "O trem chegou na estação sem atraso.",
  ]),
  ...group("fricatives", [
    "A xícara de chá esfriou na varanda.",
    "Faz frio quando a chuva chega cedo.",
    "O sofá ficou fofo depois da reforma.",
    "Vovó fez suco de fruta fresca.",
    "As folhas secas farfalham no chão.",
    "O vaso de vidro está sobre a estante.",
    "Ela fechou a janela com força.",
    "Os sapatos ficaram em cima do jornal.",
    "A fumaça sobe devagar pela chaminé.",
    "Deixei as chaves na sacola de feira.",
    "Você viu a vista da varanda hoje cedo.",
    "O zíper da jaqueta enroscou de novo.",
    "Siga sempre em frente até a esquina.",
    "Fizemos uma sopa de feijão com salsa.",
    "A vela se apaga se o vento sopra.",
  ]),
  ...group("plosives", [
    "O pato pulou do barco para o cais.",
    "Cada caixa cabe debaixo da cama.",
    "O bolo de banana queimou um pouco.",
    "Pedro pintou a porta de tinta preta.",
    "A bicicleta bateu no poste do bairro.",
    "Coloque o copo perto do prato.",
    "O gato pegou a bola debaixo da poltrona.",
    "Compramos batata, beterraba e couve.",
    "O carteiro tocou duas vezes a campainha.",
    "Tampe a panela para o caldo não secar.",
    "O tapete ficou torto depois da festa.",
    "Ela guardou o cartão dentro do bolso.",
    "O pedreiro terminou a parede à tarde.",
    "Dobre a toalha e coloque no cesto.",
    "Cabe tudo no porta-malas do carro.",
  ]),
  ...group("liquids", [
    "A lua ilumina o lago à meia-noite.",
    "Rosas vermelhas florescem no muro.",
    "O rio corre ligeiro entre as pedras.",
    "Lara leu o livro inteiro na varanda.",
    "O relógio da sala atrasa um pouco.",
    "Um colar de pérolas rolou pelo chão.",
    "O galo cantou antes do amanhecer.",
    "Lave as laranjas antes de descascar.",
    "O farol brilha sobre o mar revolto.",
    "Coloquei flores na jarra de barro.",
    "O carro parou perto da ladeira.",
    "A escola fica logo depois da curva.",
    "Ela desenrolou o lençol devagar.",
    "As luzes da rua acendem ao anoitecer.",
    "Rolou um trovão longe, atrás da serra.",
  ]),
  ...group("questions", [
    "Você quer café ou chá agora?",
    "Onde ficam as chaves do portão?",
    "A que horas o ônibus passa aqui?",
    "Já conhece a nova padaria da esquina?",
    "Podemos ir à praia no sábado?",
    "Quantos anos tem o seu cachorro?",
    "Vai chover de novo esta tarde?",
    "O mercado fecha cedo no domingo?",
    "Você prefere a janela ou o corredor?",
    "Como foi a viagem para o litoral?",
    "Alguém viu o meu guarda-chuva verde?",
    "Que filme vamos assistir hoje à noite?",
    "Será que o pão ainda está quente?",
    "Posso deixar a bicicleta aqui na entrada?",
    "Quanto custa um quilo de laranja?",
  ]),
  ...group("mixed", [
    "Quando a chuva parou, saímos para caminhar e o ar estava fresco.",
    "A padaria abre às seis, o pão sai às sete e a fila começa antes disso.",
    "Depois do almoço, li um capítulo do livro e cochilei na rede.",
    "Se o tempo firmar amanhã, vamos ao parque e levamos a pipa nova.",
    "O gato dormiu no sofá enquanto a chuva batia na janela.",
    "Guardei as compras, lavei a louça e finalmente sentei um pouco.",
    "No fim da tarde, o céu ficou laranja e o vento esfriou devagar.",
    "Ela regou as plantas, abriu as cortinas e colocou uma música baixa.",
    "A viagem foi longa, mas a estrada estava vazia e a paisagem, linda.",
    "Antes de dormir, apago as luzes, fecho a porta e deixo a janela aberta.",
    "Combinamos de sair cedo, tomar um café e pegar a primeira balsa.",
    "O trem partiu no horário, atravessou a ponte e sumiu entre os morros.",
  ]),
];
